name: iot
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Move pocketbase_utils config to root level
pocketbase_utils:
  enabled: true
  pb_schema_path: pb_schema.json
  output_dir: lib/generated/pocketbase
  line_length: 80

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel:
  http:
  timeago:
  cupertino_icons: ^1.0.6
  motif: ^0.0.6
  google_fonts: ^6.1.0
  google_generative_ai: ^0.4.6
  file_picker: ^8.1.3
  animated_text_kit: ^4.2.2
  flutter_markdown: ^0.7.4+1
  intl: ^0.20.2
  osrm: ^0.0.8
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  routing_client_dart: ^1.0.5
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.6
  lib: ^0.0.3
  pocketbase_utils: ^0.0.7
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  equatable: ^2.0.7
  collection: ^1.19.0
  pocketbase: ^0.18.1
  provider: ^6.1.2
  timeline_tile: ^2.0.0
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/doc/
    - assets/images/
